### ISSUE TITLE
Host macros

### ISSUE THREAD

**Issue by d00mst** [HenriqueCaires/ZabbixApi#8]
Hello,
Is there some interface for creating macros on the the host entity? I.e. the macros parameter on the host.create API call.
Best regards,
  Micke

**Comment by HenriqueCaires** [comment]
Hi,

For creating hostMacros by using api, is necessary the hostId, so you must create at first the host.
I prefer do not implement a method for creating a host with a hostMacro as parameter because it means that the HostService should know the HostMacro entity and the HostService purpose would be changed.
But it is OpenSource, feel free for doing your customizations.

Best regards,

Henrique

**Comment by d00mst** [comment]
Ok, thanks.
A two step process is ok with me. Now I've found the HostMacroService which does that. My problem was that before I found it I didn't have any process at all. I was also looking a bit in the wrong direction since the Zabbix API is called usermacro.
Best regards,
  Micke

**Comment by HenriqueCaires** [comment]
I have created classes following the zabbix documentation schema, but I think it would be better to separate the classes to be more intelligible, I will do that later.

Best regards,

Henrique
